"""
Analyst Agent - Reasoning Engine
Responsible for analysis and recommendations.
Uses ONLY data provided by Perceiver Agent.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
from dataclasses import dataclass, asdict
from enum import Enum
import logging
import json

logger = logging.getLogger(__name__)


class Action(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TimeHorizon(Enum):
    SHORT = "SHORT"    # < 3 months
    MEDIUM = "MEDIUM"  # 3-12 months
    LONG = "LONG"      # > 12 months


class RiskLevel(Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


@dataclass
class AnalysisResult:
    """Structured analysis output."""
    ticker: str
    company_name: str
    analysis_date: str
    action: str
    time_horizon: str
    confidence_score: float
    target_price: Optional[float]
    stop_loss: Optional[float]
    current_price: float
    rationale: Dict[str, str]
    risk_level: str
    sources_cited: List[str]
    suitability: str
    disclaimer: str


class AnalystAgent:
    """
    Reasoning Engine Agent (Analyst)

    Responsibilities:
    1. Analyze data provided by Perceiver
    2. Generate Chain-of-Thought reasoning
    3. Produce investment recommendations
    4. Cite all sources for claims

    CONSTRAINTS:
    - MUST use Chain-of-Thought reasoning
    - MUST cite sources for all claims
    - MUST NOT fetch data (only use provided data)
    - MUST NOT hallucinate figures
    """

    DISCLAIMER = """
IMPORTANT DISCLAIMER

This recommendation is AI-generated by FinAgent, an automated analysis system.
This is NOT advice from a SEBI-registered Investment Adviser.

- Past performance does not guarantee future results
- Stock investments are subject to market risks
- Please read all scheme-related documents carefully before investing
- Conduct your own due diligence or consult a qualified financial advisor

FinAgent is a tool for educational and informational purposes only.
"""

    def __init__(self):
        self.logger = logging.getLogger(__name__)

    def analyze(
        self,
        perceived_data: Dict[str, Any],
        technical_analysis: Dict[str, Any],
        user_profile: Optional[Dict[str, Any]] = None
    ) -> AnalysisResult:
        """
        Perform comprehensive stock analysis.

        Args:
            perceived_data: Data from PerceiverAgent.perceive()
            technical_analysis: Data from TechnicalAnalyzer.analyze()
            user_profile: User's risk profile (optional)

        Returns:
            AnalysisResult with recommendation
        """
        self.logger.info(f"Analyzing {perceived_data.get('ticker')}")

        ticker = perceived_data.get('ticker', 'UNKNOWN')
        company_info = perceived_data.get('company_info', {})
        market_data = perceived_data.get('market_data', {})
        sentiment_data = perceived_data.get('sentiment_data', {})
        rag_context = perceived_data.get('rag_context', {})

        # Execute Chain-of-Thought analysis
        cot_result = self._chain_of_thought_analysis(
            ticker=ticker,
            company_info=company_info,
            market_data=market_data,
            technical_analysis=technical_analysis,
            sentiment_data=sentiment_data,
            rag_context=rag_context,
            user_profile=user_profile
        )

        # Generate final recommendation
        return self._generate_recommendation(
            ticker=ticker,
            company_info=company_info,
            market_data=market_data,
            cot_result=cot_result,
            user_profile=user_profile
        )

    def _chain_of_thought_analysis(
        self,
        ticker: str,
        company_info: Dict,
        market_data: Dict,
        technical_analysis: Dict,
        sentiment_data: Dict,
        rag_context: Dict,
        user_profile: Optional[Dict]
    ) -> Dict[str, Any]:
        """
        Execute structured Chain-of-Thought analysis.

        Steps:
        1. Macro Context Analysis
        2. Fundamental Analysis
        3. Technical Analysis
        4. Risk Assessment
        5. Conclusion
        """
        result = {
            "steps": [],
            "sources_cited": []
        }

        # Step 1: Macro Context
        macro = self._analyze_macro_context(
            company_info=company_info,
            sentiment_data=sentiment_data
        )
        result["steps"].append({
            "step": 1,
            "name": "Macro Context Analysis",
            "analysis": macro
        })

        # Step 2: Fundamental Analysis
        fundamental = self._analyze_fundamentals(
            company_info=company_info,
            rag_context=rag_context
        )
        result["steps"].append({
            "step": 2,
            "name": "Fundamental Analysis",
            "analysis": fundamental
        })
        result["sources_cited"].extend(fundamental.get("sources", []))

        # Step 3: Technical Analysis
        technical = self._analyze_technicals(technical_analysis)
        result["steps"].append({
            "step": 3,
            "name": "Technical Analysis",
            "analysis": technical
        })

        # Step 4: Risk Assessment
        risk = self._assess_risk(
            technical_analysis=technical_analysis,
            company_info=company_info,
            user_profile=user_profile
        )
        result["steps"].append({
            "step": 4,
            "name": "Risk Assessment",
            "analysis": risk
        })

        # Step 5: Conclusion
        conclusion = self._synthesize_conclusion(
            macro=macro,
            fundamental=fundamental,
            technical=technical,
            risk=risk
        )
        result["steps"].append({
            "step": 5,
            "name": "Conclusion",
            "analysis": conclusion
        })

        result["conclusion"] = conclusion

        return result

    def _analyze_macro_context(
        self,
        company_info: Dict,
        sentiment_data: Dict
    ) -> Dict[str, Any]:
        """Analyze sector and market context."""
        sector = company_info.get("sector", "Unknown")
        industry = company_info.get("industry", "Unknown")

        sentiment_score = sentiment_data.get("overall_sentiment", 0)
        sentiment_trend = sentiment_data.get("sentiment_trend", "UNKNOWN")

        # Determine market mood
        if sentiment_score > 0.2:
            market_mood = "POSITIVE"
        elif sentiment_score < -0.2:
            market_mood = "NEGATIVE"
        else:
            market_mood = "NEUTRAL"

        return {
            "sector": sector,
            "industry": industry,
            "sentiment_score": sentiment_score,
            "sentiment_trend": sentiment_trend,
            "market_mood": market_mood,
            "reasoning": f"The {sector} sector is showing {sentiment_trend.lower()} sentiment with a score of {sentiment_score:.2f}. Market mood is {market_mood.lower()}."
        }

    def _analyze_fundamentals(
        self,
        company_info: Dict,
        rag_context: Dict
    ) -> Dict[str, Any]:
        """Analyze fundamental metrics."""
        # Extract key metrics (ONLY use actual data, no hallucination)
        pe_ratio = company_info.get("pe_ratio")
        pb_ratio = company_info.get("price_to_book")
        eps = company_info.get("eps")
        revenue_growth = company_info.get("revenue_growth")
        profit_margin = company_info.get("profit_margin")
        debt_to_equity = company_info.get("debt_to_equity")
        roe = company_info.get("return_on_equity")
        dividend_yield = company_info.get("dividend_yield")

        # Valuation assessment
        valuation = "UNKNOWN"
        if pe_ratio is not None:
            if pe_ratio < 15:
                valuation = "UNDERVALUED"
            elif pe_ratio > 30:
                valuation = "OVERVALUED"
            else:
                valuation = "FAIRLY_VALUED"

        # Profitability assessment
        profitability = "UNKNOWN"
        if profit_margin is not None:
            if profit_margin > 0.15:
                profitability = "STRONG"
            elif profit_margin > 0.05:
                profitability = "MODERATE"
            else:
                profitability = "WEAK"

        # Build reasoning
        reasoning_parts = []
        sources = []

        if pe_ratio is not None:
            reasoning_parts.append(f"P/E ratio of {pe_ratio:.2f}")
        if eps is not None:
            reasoning_parts.append(f"EPS of {eps:.2f}")
        if revenue_growth is not None:
            reasoning_parts.append(f"Revenue growth of {revenue_growth*100:.1f}%")
        if profit_margin is not None:
            reasoning_parts.append(f"Profit margin of {profit_margin*100:.1f}%")

        # Add sources from RAG context
        for source in rag_context.get("sources", [])[:3]:
            sources.append(source.get("doc_id", "unknown"))

        return {
            "pe_ratio": pe_ratio,
            "pb_ratio": pb_ratio,
            "eps": eps,
            "revenue_growth": revenue_growth,
            "profit_margin": profit_margin,
            "debt_to_equity": debt_to_equity,
            "roe": roe,
            "dividend_yield": dividend_yield,
            "valuation": valuation,
            "profitability": profitability,
            "reasoning": ". ".join(reasoning_parts) if reasoning_parts else "Fundamental data not available.",
            "sources": sources
        }

    def _analyze_technicals(
        self,
        technical_analysis: Dict
    ) -> Dict[str, Any]:
        """Interpret technical indicators."""
        rsi = technical_analysis.get("rsi_14")
        macd = technical_analysis.get("macd", {})
        sma_50 = technical_analysis.get("sma_50")
        sma_200 = technical_analysis.get("sma_200")
        signals = technical_analysis.get("signals", {})

        # Build technical summary
        trend = signals.get("trend", "UNKNOWN")
        rsi_signal = signals.get("rsi_signal", "UNKNOWN")
        macd_signal = signals.get("macd_signal", "UNKNOWN")

        # Overall technical assessment
        bullish_signals = 0
        bearish_signals = 0

        if rsi is not None:
            if rsi < 30:
                bullish_signals += 1
            elif rsi > 70:
                bearish_signals += 1

        if macd_signal == "BULLISH":
            bullish_signals += 1
        elif macd_signal == "BEARISH":
            bearish_signals += 1

        if trend == "UPTREND":
            bullish_signals += 1
        elif trend == "DOWNTREND":
            bearish_signals += 1

        if bullish_signals > bearish_signals:
            technical_outlook = "BULLISH"
        elif bearish_signals > bullish_signals:
            technical_outlook = "BEARISH"
        else:
            technical_outlook = "NEUTRAL"

        reasoning_parts = []
        if rsi is not None:
            reasoning_parts.append(f"RSI at {rsi:.1f} ({rsi_signal})")
        if macd.get("value") is not None:
            reasoning_parts.append(f"MACD {macd_signal}")
        if trend != "UNKNOWN":
            reasoning_parts.append(f"Price in {trend}")

        return {
            "rsi": rsi,
            "macd": macd,
            "sma_50": sma_50,
            "sma_200": sma_200,
            "trend": trend,
            "rsi_signal": rsi_signal,
            "macd_signal": macd_signal,
            "technical_outlook": technical_outlook,
            "bullish_signals": bullish_signals,
            "bearish_signals": bearish_signals,
            "reasoning": ". ".join(reasoning_parts) if reasoning_parts else "Technical data not available."
        }

    def _assess_risk(
        self,
        technical_analysis: Dict,
        company_info: Dict,
        user_profile: Optional[Dict]
    ) -> Dict[str, Any]:
        """Assess stock risk vs user tolerance."""
        beta = technical_analysis.get("beta") or company_info.get("beta")
        volatility = technical_analysis.get("volatility_30d")
        market_cap = company_info.get("market_cap")
        market_cap_category = company_info.get("market_cap_category")
        debt_to_equity = company_info.get("debt_to_equity")

        # Determine risk level
        risk_score = 0

        if beta is not None:
            if beta > 1.5:
                risk_score += 2
            elif beta > 1.0:
                risk_score += 1

        if market_cap_category == "SMALL":
            risk_score += 2
        elif market_cap_category == "MID":
            risk_score += 1

        if debt_to_equity is not None and debt_to_equity > 100:
            risk_score += 1

        if risk_score >= 4:
            risk_level = "VERY_HIGH"
        elif risk_score >= 3:
            risk_level = "HIGH"
        elif risk_score >= 1:
            risk_level = "MODERATE"
        else:
            risk_level = "LOW"

        # Check suitability if profile provided
        suitable_for = None
        if user_profile:
            user_risk = user_profile.get("risk_category", "MODERATE")

            if risk_level in ["VERY_HIGH", "HIGH"] and user_risk == "CONSERVATIVE":
                suitable_for = False
            elif risk_level == "VERY_HIGH" and user_risk == "MODERATE":
                suitable_for = False
            else:
                suitable_for = True

        return {
            "beta": beta,
            "volatility": volatility,
            "market_cap_category": market_cap_category,
            "debt_to_equity": debt_to_equity,
            "risk_level": risk_level,
            "risk_score": risk_score,
            "suitable_for_profile": suitable_for,
            "reasoning": f"Risk level is {risk_level} based on beta ({beta:.2f if beta else 'N/A'}), market cap ({market_cap_category or 'N/A'}), and leverage."
        }

    def _synthesize_conclusion(
        self,
        macro: Dict,
        fundamental: Dict,
        technical: Dict,
        risk: Dict
    ) -> Dict[str, Any]:
        """Synthesize final recommendation."""
        # Score each dimension
        scores = {
            "macro": 0,
            "fundamental": 0,
            "technical": 0
        }

        # Macro score
        if macro.get("market_mood") == "POSITIVE":
            scores["macro"] = 1
        elif macro.get("market_mood") == "NEGATIVE":
            scores["macro"] = -1

        # Fundamental score
        valuation = fundamental.get("valuation")
        profitability = fundamental.get("profitability")

        if valuation == "UNDERVALUED":
            scores["fundamental"] += 1
        elif valuation == "OVERVALUED":
            scores["fundamental"] -= 1

        if profitability == "STRONG":
            scores["fundamental"] += 1
        elif profitability == "WEAK":
            scores["fundamental"] -= 1

        # Technical score
        if technical.get("technical_outlook") == "BULLISH":
            scores["technical"] = 1
        elif technical.get("technical_outlook") == "BEARISH":
            scores["technical"] = -1

        # Total score
        total_score = scores["macro"] + scores["fundamental"] + scores["technical"]

        # Determine action
        if total_score >= 2:
            action = Action.BUY.value
            confidence = min(0.8, 0.5 + total_score * 0.1)
        elif total_score <= -2:
            action = Action.SELL.value
            confidence = min(0.8, 0.5 + abs(total_score) * 0.1)
        else:
            action = Action.HOLD.value
            confidence = 0.5

        # Determine time horizon based on technical signals
        if technical.get("trend") == "UPTREND" and fundamental.get("revenue_growth"):
            time_horizon = TimeHorizon.MEDIUM.value
        elif technical.get("rsi_signal") == "OVERSOLD":
            time_horizon = TimeHorizon.SHORT.value
        else:
            time_horizon = TimeHorizon.LONG.value

        return {
            "action": action,
            "time_horizon": time_horizon,
            "confidence": confidence,
            "scores": scores,
            "total_score": total_score,
            "risk_level": risk.get("risk_level"),
            "reasoning": f"Based on {macro.get('market_mood', 'neutral')} market sentiment, {fundamental.get('valuation', 'unknown')} valuation, and {technical.get('technical_outlook', 'neutral')} technical outlook."
        }

    def _generate_recommendation(
        self,
        ticker: str,
        company_info: Dict,
        market_data: Dict,
        cot_result: Dict,
        user_profile: Optional[Dict]
    ) -> AnalysisResult:
        """Generate final structured recommendation."""
        conclusion = cot_result.get("conclusion", {})
        steps = cot_result.get("steps", [])

        # Extract rationale from steps
        rationale = {}
        for step in steps:
            name = step.get("name", "").lower().replace(" ", "_")
            analysis = step.get("analysis", {})
            rationale[name] = analysis.get("reasoning", "")

        # Determine suitability
        risk_step = next((s for s in steps if s.get("name") == "Risk Assessment"), {})
        risk_analysis = risk_step.get("analysis", {})

        if user_profile:
            profile_category = user_profile.get("risk_category", "MODERATE")
            suitability = f"Suitable for {profile_category} profiles" if risk_analysis.get("suitable_for_profile") else f"NOT suitable for {profile_category} profiles"
        else:
            suitability = f"Suitable for {conclusion.get('risk_level', 'MODERATE')}-risk tolerance investors"

        current_price = market_data.get("price")

        return AnalysisResult(
            ticker=ticker,
            company_name=company_info.get("name", ticker),
            analysis_date=datetime.now().strftime("%Y-%m-%d"),
            action=conclusion.get("action", Action.HOLD.value),
            time_horizon=conclusion.get("time_horizon", TimeHorizon.MEDIUM.value),
            confidence_score=conclusion.get("confidence", 0.5),
            target_price=None,  # Do not hallucinate target prices
            stop_loss=None,     # Do not hallucinate stop losses
            current_price=current_price,
            rationale=rationale,
            risk_level=conclusion.get("risk_level", "MODERATE"),
            sources_cited=cot_result.get("sources_cited", []),
            suitability=suitability,
            disclaimer=self.DISCLAIMER
        )

    def format_analysis_report(self, result: AnalysisResult) -> str:
        """Format analysis result as a readable report."""
        report = f"""
{'='*60}
STOCK ANALYSIS REPORT
{'='*60}

Ticker: {result.ticker}
Company: {result.company_name}
Analysis Date: {result.analysis_date}

{'─'*60}
RECOMMENDATION
{'─'*60}
Action: {result.action}
Time Horizon: {result.time_horizon}
Confidence: {result.confidence_score:.0%}
Risk Level: {result.risk_level}

Current Price: {result.current_price if result.current_price else 'N/A'}

{'─'*60}
ANALYSIS RATIONALE
{'─'*60}
"""

        for category, reasoning in result.rationale.items():
            if reasoning:
                report += f"\n{category.replace('_', ' ').title()}:\n{reasoning}\n"

        report += f"""
{'─'*60}
SUITABILITY
{'─'*60}
{result.suitability}

{'─'*60}
SOURCES CITED
{'─'*60}
"""
        for source in result.sources_cited[:5]:
            report += f"- {source}\n"

        report += f"""
{'='*60}
{result.disclaimer}
{'='*60}
"""
        return report

    def to_json(self, result: AnalysisResult) -> str:
        """Convert analysis result to JSON."""
        return json.dumps(asdict(result), indent=2, default=str)
