"""
Chain-of-Thought Synthesizer
Structured reasoning for investment recommendations.
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass, asdict
from enum import Enum
from datetime import datetime
import logging
import json

logger = logging.getLogger(__name__)


class Action(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class TimeHorizon(Enum):
    SHORT = "SHORT"    # < 3 months
    MEDIUM = "MEDIUM"  # 3-12 months
    LONG = "LONG"      # > 12 months


@dataclass
class Recommendation:
    """Structured investment recommendation."""
    ticker: str
    company_name: str
    action: str
    time_horizon: str
    confidence_score: float
    target_price: Optional[float]
    stop_loss: Optional[float]
    current_price: float
    rationale: Dict[str, str]
    sources_cited: List[str]
    suitability: str
    risk_level: str
    disclaimer: str

    def to_dict(self) -> Dict:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, default=str)


class ChainOfThoughtSynthesizer:
    """
    Implements structured reasoning chain for analysis.

    Chain:
    1. MACRO: Market/sector context from news sentiment
    2. FUNDAMENTAL: Financial metrics from company data
    3. TECHNICAL: Price indicators from TA module
    4. RISK: Volatility vs user tolerance
    5. CONCLUSION: Final recommendation

    IMPORTANT:
    - All reasoning is based on provided data only
    - No hallucination of figures
    - All claims must be citable
    """

    REASONING_TEMPLATE = """
## Analysis for {ticker} - {company_name}

### Step 1: Macro Context Analysis
Sector: {sector}
Market Sentiment: {market_sentiment}
Sector Sentiment: {sector_sentiment}
Key Macro Factors: {macro_factors}

### Step 2: Fundamental Analysis
Data Source: {fundamental_sources}
Revenue (Latest): {revenue} ({revenue_growth} YoY)
Net Profit: {net_profit} ({profit_growth} YoY)
EPS: {eps}
P/E Ratio: {pe_ratio}
Debt-to-Equity: {debt_equity}
Fundamental Assessment: {fundamental_assessment}

### Step 3: Technical Analysis
Current Price: {current_price}
RSI (14): {rsi} - {rsi_interpretation}
MACD: {macd} - {macd_interpretation}
50-DMA: {sma_50} | 200-DMA: {sma_200}
Trend: {trend}
Technical Assessment: {technical_assessment}

### Step 4: Risk Assessment
Beta: {beta}
30-Day Volatility: {volatility}
User Risk Profile: {user_risk_profile}
Risk Assessment: {risk_assessment}

### Step 5: Conclusion
Action: {action}
Time Horizon: {time_horizon}
Confidence: {confidence}
Rationale: {conclusion_rationale}

Sources Cited: {sources}
"""

    DISCLAIMER = """
IMPORTANT DISCLAIMER

This recommendation is AI-generated by FinAgent, an automated analysis system.
This is NOT advice from a SEBI-registered Investment Adviser.

- Past performance does not guarantee future results
- Stock investments are subject to market risks
- Please read all scheme-related documents carefully before investing
- Conduct your own due diligence or consult a qualified financial advisor

FinAgent is a tool for educational and informational purposes only.
"""

    def __init__(self):
        self.logger = logging.getLogger(__name__)

    def synthesize(
        self,
        ticker: str,
        market_data: Dict,
        technical_data: Dict,
        fundamental_data: Dict,
        sentiment_data: Dict,
        rag_context: Dict,
        user_profile: Optional[Dict] = None
    ) -> Recommendation:
        """
        Execute chain-of-thought analysis.

        All data must be pre-fetched and verified.
        This method reasons over the data, it does NOT fetch.

        Args:
            ticker: Stock ticker symbol
            market_data: Live market data
            technical_data: Technical analysis results
            fundamental_data: Company fundamentals
            sentiment_data: News sentiment
            rag_context: Retrieved document context
            user_profile: User's risk profile

        Returns:
            Recommendation with full rationale
        """
        self.logger.info(f"Synthesizing recommendation for {ticker}")

        # Step 1: Macro Context
        macro_assessment = self._assess_macro(
            fundamental_data=fundamental_data,
            sentiment_data=sentiment_data
        )

        # Step 2: Fundamental Assessment
        fundamental_assessment = self._assess_fundamentals(
            fundamental_data=fundamental_data,
            rag_context=rag_context
        )

        # Step 3: Technical Assessment
        technical_assessment = self._assess_technicals(
            technical_data=technical_data
        )

        # Step 4: Risk Assessment
        risk_assessment = self._assess_risk(
            technical_data=technical_data,
            fundamental_data=fundamental_data,
            user_profile=user_profile
        )

        # Step 5: Generate Conclusion
        conclusion = self._generate_conclusion(
            macro=macro_assessment,
            fundamental=fundamental_assessment,
            technical=technical_assessment,
            risk=risk_assessment
        )

        # Build recommendation
        current_price = market_data.get("price")
        company_name = fundamental_data.get("name", ticker)

        # Collect sources
        sources = []
        for source in rag_context.get("sources", [])[:5]:
            sources.append(source.get("doc_id", "unknown"))

        # Determine suitability
        suitability = self._determine_suitability(
            risk_level=risk_assessment.get("risk_level"),
            user_profile=user_profile
        )

        # Build rationale
        rationale = {
            "macro_context": macro_assessment.get("summary", ""),
            "fundamental_analysis": fundamental_assessment.get("summary", ""),
            "technical_analysis": technical_assessment.get("summary", ""),
            "risk_factors": risk_assessment.get("summary", ""),
            "catalyst": self._identify_catalysts(
                technical_data, sentiment_data, rag_context
            )
        }

        return Recommendation(
            ticker=ticker,
            company_name=company_name,
            action=conclusion.get("action", Action.HOLD.value),
            time_horizon=conclusion.get("time_horizon", TimeHorizon.MEDIUM.value),
            confidence_score=conclusion.get("confidence", 0.5),
            target_price=None,  # We don't hallucinate targets
            stop_loss=None,     # We don't hallucinate stop losses
            current_price=current_price,
            rationale=rationale,
            sources_cited=sources,
            suitability=suitability,
            risk_level=risk_assessment.get("risk_level", "MODERATE"),
            disclaimer=self.DISCLAIMER
        )

    def _assess_macro(
        self,
        fundamental_data: Dict,
        sentiment_data: Dict
    ) -> Dict[str, Any]:
        """Analyze macro and sector context."""
        sector = fundamental_data.get("sector", "Unknown")
        industry = fundamental_data.get("industry", "Unknown")

        # Get sentiment scores
        overall_sentiment = sentiment_data.get("overall_sentiment", 0)
        sentiment_trend = sentiment_data.get("sentiment_trend", "UNKNOWN")

        # Determine sector mood
        if overall_sentiment > 0.2:
            sector_mood = "POSITIVE"
            sentiment_impact = 1
        elif overall_sentiment < -0.2:
            sector_mood = "NEGATIVE"
            sentiment_impact = -1
        else:
            sector_mood = "NEUTRAL"
            sentiment_impact = 0

        summary_parts = []
        summary_parts.append(f"Sector: {sector}")
        summary_parts.append(f"Sentiment: {sentiment_trend}")

        if sentiment_data.get("recent_headlines"):
            top_headline = sentiment_data["recent_headlines"][0]
            summary_parts.append(f"Recent news: {top_headline.get('headline', '')[:100]}")

        return {
            "sector": sector,
            "industry": industry,
            "sentiment_score": overall_sentiment,
            "sentiment_trend": sentiment_trend,
            "sector_mood": sector_mood,
            "sentiment_impact": sentiment_impact,
            "summary": ". ".join(summary_parts)
        }

    def _assess_fundamentals(
        self,
        fundamental_data: Dict,
        rag_context: Dict
    ) -> Dict[str, Any]:
        """Analyze fundamental metrics with citations."""
        summary_parts = []
        sources = []

        # Extract key metrics
        pe_ratio = fundamental_data.get("pe_ratio")
        eps = fundamental_data.get("eps")
        revenue_growth = fundamental_data.get("revenue_growth")
        profit_margin = fundamental_data.get("profit_margin")
        roe = fundamental_data.get("return_on_equity")
        debt_to_equity = fundamental_data.get("debt_to_equity")

        # Valuation assessment
        valuation_score = 0
        if pe_ratio is not None:
            if pe_ratio < 15:
                valuation_score = 2
                summary_parts.append(f"Attractively valued at P/E {pe_ratio:.1f}")
            elif pe_ratio > 30:
                valuation_score = -2
                summary_parts.append(f"Premium valuation with P/E {pe_ratio:.1f}")
            else:
                valuation_score = 0
                summary_parts.append(f"P/E at {pe_ratio:.1f}")

        # Profitability
        profitability_score = 0
        if profit_margin is not None:
            margin_pct = profit_margin * 100 if profit_margin < 1 else profit_margin
            if margin_pct > 15:
                profitability_score = 2
                summary_parts.append(f"Strong profitability ({margin_pct:.1f}% margin)")
            elif margin_pct > 5:
                profitability_score = 1
                summary_parts.append(f"Good profitability ({margin_pct:.1f}% margin)")
            else:
                profitability_score = -1
                summary_parts.append(f"Low profitability ({margin_pct:.1f}% margin)")

        # Growth
        growth_score = 0
        if revenue_growth is not None:
            growth_pct = revenue_growth * 100 if abs(revenue_growth) < 5 else revenue_growth
            if growth_pct > 15:
                growth_score = 2
                summary_parts.append(f"Strong growth ({growth_pct:.1f}% revenue growth)")
            elif growth_pct > 0:
                growth_score = 1
                summary_parts.append(f"Positive growth ({growth_pct:.1f}%)")
            else:
                growth_score = -1
                summary_parts.append(f"Negative growth ({growth_pct:.1f}%)")

        # Get sources from RAG context
        for source in rag_context.get("sources", [])[:3]:
            sources.append(source.get("doc_id", ""))

        # Overall fundamental assessment
        total_score = valuation_score + profitability_score + growth_score

        if total_score >= 3:
            assessment = "VERY_POSITIVE"
        elif total_score >= 1:
            assessment = "POSITIVE"
        elif total_score <= -3:
            assessment = "VERY_NEGATIVE"
        elif total_score <= -1:
            assessment = "NEGATIVE"
        else:
            assessment = "NEUTRAL"

        return {
            "pe_ratio": pe_ratio,
            "eps": eps,
            "revenue_growth": revenue_growth,
            "profit_margin": profit_margin,
            "roe": roe,
            "debt_to_equity": debt_to_equity,
            "valuation_score": valuation_score,
            "profitability_score": profitability_score,
            "growth_score": growth_score,
            "total_score": total_score,
            "assessment": assessment,
            "sources": sources,
            "summary": ". ".join(summary_parts) if summary_parts else "Fundamental data not available"
        }

    def _assess_technicals(self, technical_data: Dict) -> Dict[str, Any]:
        """Interpret technical indicators."""
        summary_parts = []

        rsi = technical_data.get("rsi_14")
        macd = technical_data.get("macd", {})
        signals = technical_data.get("signals", {})
        trend = signals.get("trend", "UNKNOWN")

        # Technical score
        tech_score = 0

        # RSI interpretation
        if rsi is not None:
            rsi_signal = signals.get("rsi_signal", "NEUTRAL")
            if rsi < 30:
                tech_score += 2
                summary_parts.append(f"RSI at {rsi:.1f} (OVERSOLD)")
            elif rsi > 70:
                tech_score -= 2
                summary_parts.append(f"RSI at {rsi:.1f} (OVERBOUGHT)")
            else:
                summary_parts.append(f"RSI at {rsi:.1f} ({rsi_signal})")

        # MACD interpretation
        macd_signal = signals.get("macd_signal", "NEUTRAL")
        if macd_signal == "BULLISH":
            tech_score += 1
            summary_parts.append("MACD bullish crossover")
        elif macd_signal == "BEARISH":
            tech_score -= 1
            summary_parts.append("MACD bearish crossover")

        # Trend interpretation
        if trend == "UPTREND":
            tech_score += 1
            summary_parts.append("Price in uptrend")
        elif trend == "DOWNTREND":
            tech_score -= 1
            summary_parts.append("Price in downtrend")
        else:
            summary_parts.append("Sideways movement")

        # Golden/Death Cross
        if technical_data.get("golden_cross"):
            tech_score += 1
            summary_parts.append("Golden cross pattern")
        elif technical_data.get("death_cross"):
            tech_score -= 1
            summary_parts.append("Death cross pattern")

        # Overall technical assessment
        if tech_score >= 3:
            assessment = "STRONGLY_BULLISH"
        elif tech_score >= 1:
            assessment = "BULLISH"
        elif tech_score <= -3:
            assessment = "STRONGLY_BEARISH"
        elif tech_score <= -1:
            assessment = "BEARISH"
        else:
            assessment = "NEUTRAL"

        return {
            "rsi": rsi,
            "macd": macd,
            "trend": trend,
            "tech_score": tech_score,
            "assessment": assessment,
            "summary": ". ".join(summary_parts) if summary_parts else "Technical data not available"
        }

    def _assess_risk(
        self,
        technical_data: Dict,
        fundamental_data: Dict,
        user_profile: Optional[Dict]
    ) -> Dict[str, Any]:
        """Assess stock risk vs user tolerance."""
        beta = technical_data.get("beta") or fundamental_data.get("beta")
        volatility = technical_data.get("volatility_30d")
        market_cap_category = fundamental_data.get("market_cap_category")
        debt_to_equity = fundamental_data.get("debt_to_equity")

        # Calculate risk score
        risk_score = 0
        summary_parts = []

        if beta is not None:
            if beta > 1.5:
                risk_score += 3
                summary_parts.append(f"High beta ({beta:.2f})")
            elif beta > 1.0:
                risk_score += 1
                summary_parts.append(f"Above-market beta ({beta:.2f})")
            elif beta < 0.8:
                summary_parts.append(f"Low beta ({beta:.2f})")

        if volatility is not None:
            if volatility > 0.5:
                risk_score += 2
                summary_parts.append(f"High volatility ({volatility*100:.1f}%)")
            elif volatility > 0.3:
                risk_score += 1
                summary_parts.append(f"Moderate volatility ({volatility*100:.1f}%)")

        if market_cap_category == "SMALL":
            risk_score += 2
            summary_parts.append("Small-cap stock")
        elif market_cap_category == "MID":
            risk_score += 1
            summary_parts.append("Mid-cap stock")

        if debt_to_equity is not None and debt_to_equity > 100:
            risk_score += 1
            summary_parts.append("Elevated leverage")

        # Determine risk level
        if risk_score >= 5:
            risk_level = "VERY_HIGH"
        elif risk_score >= 3:
            risk_level = "HIGH"
        elif risk_score >= 1:
            risk_level = "MODERATE"
        else:
            risk_level = "LOW"

        # Check suitability if profile provided
        suitable_for_profile = None
        if user_profile:
            user_risk = user_profile.get("risk_category", "MODERATE")
            if risk_level in ["VERY_HIGH", "HIGH"] and user_risk == "CONSERVATIVE":
                suitable_for_profile = False
            elif risk_level == "VERY_HIGH" and user_risk == "MODERATE":
                suitable_for_profile = False
            else:
                suitable_for_profile = True

        return {
            "beta": beta,
            "volatility": volatility,
            "market_cap_category": market_cap_category,
            "risk_score": risk_score,
            "risk_level": risk_level,
            "suitable_for_profile": suitable_for_profile,
            "summary": ". ".join(summary_parts) if summary_parts else "Risk assessment not available"
        }

    def _generate_conclusion(
        self,
        macro: Dict,
        fundamental: Dict,
        technical: Dict,
        risk: Dict
    ) -> Dict[str, Any]:
        """Synthesize final recommendation."""
        # Calculate weighted scores
        macro_impact = macro.get("sentiment_impact", 0)  # -1 to 1
        fundamental_score = fundamental.get("total_score", 0)  # typically -6 to 6
        technical_score = technical.get("tech_score", 0)  # typically -5 to 5

        # Normalize scores to -10 to 10 range
        normalized_fundamental = fundamental_score * 1.5
        normalized_technical = technical_score * 2
        normalized_macro = macro_impact * 2

        # Weight the scores
        total_score = (
            normalized_fundamental * 0.4 +
            normalized_technical * 0.35 +
            normalized_macro * 0.25
        )

        # Determine action
        if total_score >= 4:
            action = Action.BUY.value
            confidence = min(0.85, 0.5 + total_score * 0.05)
        elif total_score <= -4:
            action = Action.SELL.value
            confidence = min(0.85, 0.5 + abs(total_score) * 0.05)
        else:
            action = Action.HOLD.value
            confidence = 0.5 + abs(total_score) * 0.02

        # Determine time horizon
        if technical.get("trend") == "UPTREND" and fundamental.get("growth_score", 0) > 0:
            time_horizon = TimeHorizon.MEDIUM.value
        elif technical.get("rsi") and technical["rsi"] < 30:
            time_horizon = TimeHorizon.SHORT.value
        elif fundamental.get("total_score", 0) >= 4:
            time_horizon = TimeHorizon.LONG.value
        else:
            time_horizon = TimeHorizon.MEDIUM.value

        # Adjust confidence for risk
        if risk.get("risk_level") == "VERY_HIGH":
            confidence *= 0.8

        return {
            "action": action,
            "time_horizon": time_horizon,
            "confidence": round(confidence, 2),
            "total_score": round(total_score, 2),
            "component_scores": {
                "macro": normalized_macro,
                "fundamental": normalized_fundamental,
                "technical": normalized_technical
            }
        }

    def _determine_suitability(
        self,
        risk_level: str,
        user_profile: Optional[Dict]
    ) -> str:
        """Determine suitability statement."""
        if not user_profile:
            suitability_map = {
                "LOW": "Suitable for all risk profiles",
                "MODERATE": "Suitable for Moderate and Aggressive profiles",
                "HIGH": "Suitable for Aggressive profiles only",
                "VERY_HIGH": "Only for highly risk-tolerant investors"
            }
            return suitability_map.get(risk_level, "Review risk factors carefully")

        profile_category = user_profile.get("risk_category", "MODERATE")

        if risk_level in ["VERY_HIGH", "HIGH"] and profile_category == "CONSERVATIVE":
            return f"NOT SUITABLE for {profile_category} profile - risk level too high"
        elif risk_level == "VERY_HIGH" and profile_category == "MODERATE":
            return f"NOT SUITABLE for {profile_category} profile - risk level too high"
        else:
            return f"SUITABLE for {profile_category} profile"

    def _identify_catalysts(
        self,
        technical_data: Dict,
        sentiment_data: Dict,
        rag_context: Dict
    ) -> str:
        """Identify potential price catalysts."""
        catalysts = []

        # Technical catalysts
        if technical_data.get("golden_cross"):
            catalysts.append("Recent golden cross pattern")
        if technical_data.get("death_cross"):
            catalysts.append("Recent death cross pattern")

        rsi = technical_data.get("rsi_14")
        if rsi and rsi < 25:
            catalysts.append("Extreme oversold conditions")
        elif rsi and rsi > 75:
            catalysts.append("Extreme overbought conditions")

        # Sentiment catalysts
        sentiment_trend = sentiment_data.get("sentiment_trend")
        if sentiment_trend == "STRONGLY_POSITIVE":
            catalysts.append("Strong positive news sentiment")
        elif sentiment_trend == "STRONGLY_NEGATIVE":
            catalysts.append("Negative news sentiment")

        # From recent news
        if sentiment_data.get("recent_headlines"):
            top_headline = sentiment_data["recent_headlines"][0]
            if abs(top_headline.get("sentiment", 0)) > 0.5:
                catalysts.append(f"News: {top_headline.get('headline', '')[:80]}...")

        return ". ".join(catalysts) if catalysts else "No specific near-term catalysts identified"

    def format_recommendation_report(self, rec: Recommendation) -> str:
        """Format recommendation as a readable report."""
        report = f"""
{'='*70}
INVESTMENT RECOMMENDATION REPORT
{'='*70}

Ticker: {rec.ticker}
Company: {rec.company_name}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}

{'─'*70}
RECOMMENDATION SUMMARY
{'─'*70}

Action: {rec.action}
Time Horizon: {rec.time_horizon}
Confidence: {rec.confidence_score:.0%}
Risk Level: {rec.risk_level}
Current Price: {rec.current_price if rec.current_price else 'N/A'}

Suitability: {rec.suitability}

{'─'*70}
ANALYSIS RATIONALE
{'─'*70}
"""

        for category, reasoning in rec.rationale.items():
            if reasoning:
                report += f"\n{category.replace('_', ' ').title()}:\n{reasoning}\n"

        report += f"""
{'─'*70}
SOURCES CITED
{'─'*70}
"""
        for source in rec.sources_cited[:5]:
            report += f"- {source}\n"

        if not rec.sources_cited:
            report += "- Market data from yfinance\n"

        report += f"""
{'='*70}
{rec.disclaimer}
{'='*70}
"""
        return report

    def generate_chain_of_thought_log(
        self,
        rec: Recommendation,
        assessments: Dict
    ) -> str:
        """Generate detailed chain-of-thought reasoning log."""
        return self.REASONING_TEMPLATE.format(
            ticker=rec.ticker,
            company_name=rec.company_name,
            sector=assessments.get("macro", {}).get("sector", "N/A"),
            market_sentiment=assessments.get("macro", {}).get("sentiment_trend", "N/A"),
            sector_sentiment=assessments.get("macro", {}).get("sector_mood", "N/A"),
            macro_factors=assessments.get("macro", {}).get("summary", "N/A"),
            fundamental_sources=", ".join(assessments.get("fundamental", {}).get("sources", [])),
            revenue="N/A",
            revenue_growth=assessments.get("fundamental", {}).get("revenue_growth", "N/A"),
            net_profit="N/A",
            profit_growth="N/A",
            eps=assessments.get("fundamental", {}).get("eps", "N/A"),
            pe_ratio=assessments.get("fundamental", {}).get("pe_ratio", "N/A"),
            debt_equity=assessments.get("fundamental", {}).get("debt_to_equity", "N/A"),
            fundamental_assessment=assessments.get("fundamental", {}).get("assessment", "N/A"),
            current_price=rec.current_price,
            rsi=assessments.get("technical", {}).get("rsi", "N/A"),
            rsi_interpretation=assessments.get("technical", {}).get("assessment", "N/A"),
            macd=assessments.get("technical", {}).get("macd", "N/A"),
            macd_interpretation=assessments.get("technical", {}).get("assessment", "N/A"),
            sma_50="N/A",
            sma_200="N/A",
            trend=assessments.get("technical", {}).get("trend", "N/A"),
            technical_assessment=assessments.get("technical", {}).get("assessment", "N/A"),
            beta=assessments.get("risk", {}).get("beta", "N/A"),
            volatility=assessments.get("risk", {}).get("volatility", "N/A"),
            user_risk_profile=assessments.get("risk", {}).get("suitable_for_profile", "N/A"),
            risk_assessment=assessments.get("risk", {}).get("risk_level", "N/A"),
            action=rec.action,
            time_horizon=rec.time_horizon,
            confidence=f"{rec.confidence_score:.0%}",
            conclusion_rationale=rec.rationale.get("catalyst", "N/A"),
            sources=", ".join(rec.sources_cited)
        )
