"""
Compliance Logger
SEBI-mandated audit trail for all interactions.
"""

import sqlite3
import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, Any, Optional, List
import uuid
import logging
import hashlib

logger = logging.getLogger(__name__)


DISCLAIMER_TEXT = """
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
IMPORTANT DISCLAIMER

This recommendation is AI-generated by FinAgent, an automated analysis system.
This is NOT advice from a SEBI-registered Investment Adviser.

• Past performance does not guarantee future results
• Stock investments are subject to market risks
• Please read all scheme-related documents carefully before investing
• Conduct your own due diligence or consult a qualified financial advisor

FinAgent is a tool for educational and informational purposes only.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""


class ComplianceLogger:
    """
    Maintains 5-year audit trail of all interactions.

    SEBI Requirements:
    - Store all advice given
    - Store user queries
    - Store data sources used
    - Store risk profile at time of advice
    - Retention period: 5 years minimum
    """

    RETENTION_YEARS = 5

    def __init__(self, db_path: str = "logs/compliance.db"):
        self.db_path = Path(db_path)
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.logger = logging.getLogger(__name__)
        self._init_db()

    def _init_db(self):
        """Initialize compliance database."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Main interactions table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS interactions (
                id TEXT PRIMARY KEY,
                timestamp TEXT NOT NULL,
                user_id TEXT,
                session_id TEXT,
                interaction_type TEXT NOT NULL,
                query TEXT,
                response TEXT,
                recommendation_json TEXT,
                sources_used TEXT,
                risk_profile_id TEXT,
                risk_profile_snapshot TEXT,
                data_sources_json TEXT,
                metadata_json TEXT,
                checksum TEXT
            )
        """)

        # Recommendations table (detailed)
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS recommendations (
                id TEXT PRIMARY KEY,
                interaction_id TEXT NOT NULL,
                ticker TEXT NOT NULL,
                action TEXT NOT NULL,
                confidence REAL,
                rationale TEXT,
                risk_level TEXT,
                created_at TEXT NOT NULL,
                FOREIGN KEY (interaction_id) REFERENCES interactions(id)
            )
        """)

        # Data access log
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS data_access_log (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                interaction_id TEXT,
                data_source TEXT NOT NULL,
                data_type TEXT NOT NULL,
                ticker TEXT,
                accessed_at TEXT NOT NULL,
                success INTEGER,
                error_message TEXT
            )
        """)

        # Risk profile history
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS risk_profile_history (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                profile_id TEXT NOT NULL,
                user_id TEXT,
                category TEXT NOT NULL,
                score INTEGER,
                constraints_json TEXT,
                created_at TEXT NOT NULL
            )
        """)

        # Create indexes
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_interactions_timestamp
            ON interactions(timestamp)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_interactions_user
            ON interactions(user_id)
        """)
        cursor.execute("""
            CREATE INDEX IF NOT EXISTS idx_recommendations_ticker
            ON recommendations(ticker)
        """)

        conn.commit()
        conn.close()
        self.logger.info(f"Compliance database initialized at {self.db_path}")

    def _generate_checksum(self, data: str) -> str:
        """Generate checksum for data integrity verification."""
        return hashlib.sha256(data.encode()).hexdigest()

    def log_interaction(
        self,
        interaction_type: str,
        query: Optional[str],
        response: str,
        recommendation: Optional[Dict] = None,
        sources: Optional[List] = None,
        risk_profile: Optional[Dict] = None,
        user_id: Optional[str] = None,
        session_id: Optional[str] = None,
        metadata: Optional[Dict] = None
    ) -> str:
        """
        Log an interaction for compliance.

        Args:
            interaction_type: Type of interaction (analysis, recommendation, query, etc.)
            query: User's original query
            response: System's response
            recommendation: Structured recommendation if any
            sources: Data sources used
            risk_profile: User's risk profile at time of interaction
            user_id: User identifier
            session_id: Session identifier
            metadata: Additional metadata

        Returns:
            interaction_id: Unique identifier for this interaction
        """
        interaction_id = str(uuid.uuid4())
        timestamp = datetime.utcnow().isoformat()

        # Prepare data for storage
        sources_json = json.dumps(sources) if sources else None
        recommendation_json = json.dumps(recommendation) if recommendation else None
        profile_snapshot = json.dumps(risk_profile) if risk_profile else None
        metadata_json = json.dumps(metadata) if metadata else None

        # Generate checksum for integrity
        checksum_data = f"{timestamp}:{query}:{response}:{recommendation_json}"
        checksum = self._generate_checksum(checksum_data)

        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        try:
            cursor.execute("""
                INSERT INTO interactions
                (id, timestamp, user_id, session_id, interaction_type,
                 query, response, recommendation_json, sources_used,
                 risk_profile_id, risk_profile_snapshot, metadata_json, checksum)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                interaction_id,
                timestamp,
                user_id,
                session_id,
                interaction_type,
                query,
                response[:10000] if response else None,  # Limit response size
                recommendation_json,
                sources_json,
                risk_profile.get("profile_id") if risk_profile else None,
                profile_snapshot,
                metadata_json,
                checksum
            ))

            # Log recommendation details if present
            if recommendation:
                cursor.execute("""
                    INSERT INTO recommendations
                    (id, interaction_id, ticker, action, confidence, rationale, risk_level, created_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    str(uuid.uuid4()),
                    interaction_id,
                    recommendation.get("ticker", "UNKNOWN"),
                    recommendation.get("action", "UNKNOWN"),
                    recommendation.get("confidence_score"),
                    json.dumps(recommendation.get("rationale")),
                    recommendation.get("risk_level"),
                    timestamp
                ))

            conn.commit()
            self.logger.info(f"Logged interaction: {interaction_id} ({interaction_type})")

        except Exception as e:
            self.logger.error(f"Error logging interaction: {e}")
            conn.rollback()
            raise

        finally:
            conn.close()

        return interaction_id

    def log_data_access(
        self,
        data_source: str,
        data_type: str,
        ticker: Optional[str] = None,
        interaction_id: Optional[str] = None,
        success: bool = True,
        error_message: Optional[str] = None
    ):
        """Log data access for audit trail."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("""
            INSERT INTO data_access_log
            (interaction_id, data_source, data_type, ticker, accessed_at, success, error_message)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        """, (
            interaction_id,
            data_source,
            data_type,
            ticker,
            datetime.utcnow().isoformat(),
            1 if success else 0,
            error_message
        ))

        conn.commit()
        conn.close()

    def log_risk_profile(self, profile: Dict, user_id: Optional[str] = None):
        """Log risk profile creation/update."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("""
            INSERT INTO risk_profile_history
            (profile_id, user_id, category, score, constraints_json, created_at)
            VALUES (?, ?, ?, ?, ?, ?)
        """, (
            profile.get("profile_id"),
            user_id,
            profile.get("risk_category"),
            profile.get("risk_score"),
            json.dumps(profile.get("constraints")),
            datetime.utcnow().isoformat()
        ))

        conn.commit()
        conn.close()

    def get_audit_trail(
        self,
        user_id: Optional[str] = None,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None,
        interaction_type: Optional[str] = None,
        limit: int = 100
    ) -> List[Dict]:
        """Retrieve audit trail for compliance review."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        sql = "SELECT * FROM interactions WHERE 1=1"
        params = []

        if user_id:
            sql += " AND user_id = ?"
            params.append(user_id)

        if start_date:
            sql += " AND timestamp >= ?"
            params.append(start_date)

        if end_date:
            sql += " AND timestamp <= ?"
            params.append(end_date)

        if interaction_type:
            sql += " AND interaction_type = ?"
            params.append(interaction_type)

        sql += " ORDER BY timestamp DESC LIMIT ?"
        params.append(limit)

        cursor.execute(sql, params)
        rows = cursor.fetchall()
        conn.close()

        return [dict(row) for row in rows]

    def get_recommendation_history(
        self,
        ticker: Optional[str] = None,
        start_date: Optional[str] = None,
        limit: int = 50
    ) -> List[Dict]:
        """Get history of recommendations."""
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()

        sql = "SELECT * FROM recommendations WHERE 1=1"
        params = []

        if ticker:
            sql += " AND ticker = ?"
            params.append(ticker)

        if start_date:
            sql += " AND created_at >= ?"
            params.append(start_date)

        sql += " ORDER BY created_at DESC LIMIT ?"
        params.append(limit)

        cursor.execute(sql, params)
        rows = cursor.fetchall()
        conn.close()

        return [dict(row) for row in rows]

    def verify_integrity(self, interaction_id: str) -> bool:
        """Verify data integrity using checksum."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT timestamp, query, response, recommendation_json, checksum
            FROM interactions WHERE id = ?
        """, (interaction_id,))

        row = cursor.fetchone()
        conn.close()

        if not row:
            return False

        timestamp, query, response, recommendation_json, stored_checksum = row
        computed_checksum = self._generate_checksum(
            f"{timestamp}:{query}:{response}:{recommendation_json}"
        )

        return computed_checksum == stored_checksum

    def cleanup_old_records(self) -> int:
        """
        Remove records older than retention period.

        Note: Only run this after proper archival in production.
        """
        cutoff = (datetime.utcnow() - timedelta(days=self.RETENTION_YEARS * 365)).isoformat()

        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Get IDs to delete
        cursor.execute(
            "SELECT id FROM interactions WHERE timestamp < ?",
            (cutoff,)
        )
        old_ids = [row[0] for row in cursor.fetchall()]

        if old_ids:
            # Delete related records
            placeholders = ",".join("?" * len(old_ids))
            cursor.execute(
                f"DELETE FROM recommendations WHERE interaction_id IN ({placeholders})",
                old_ids
            )
            cursor.execute(
                f"DELETE FROM data_access_log WHERE interaction_id IN ({placeholders})",
                old_ids
            )
            cursor.execute(
                f"DELETE FROM interactions WHERE id IN ({placeholders})",
                old_ids
            )

        conn.commit()
        conn.close()

        self.logger.warning(f"Cleaned up {len(old_ids)} old records")
        return len(old_ids)

    def get_compliance_summary(self) -> Dict:
        """Get summary statistics for compliance reporting."""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()

        # Total interactions
        cursor.execute("SELECT COUNT(*) FROM interactions")
        total_interactions = cursor.fetchone()[0]

        # Interactions by type
        cursor.execute("""
            SELECT interaction_type, COUNT(*) as count
            FROM interactions
            GROUP BY interaction_type
        """)
        by_type = {row[0]: row[1] for row in cursor.fetchall()}

        # Recent recommendations
        cursor.execute("""
            SELECT COUNT(*) FROM recommendations
            WHERE created_at >= ?
        """, ((datetime.utcnow() - timedelta(days=30)).isoformat(),))
        recent_recommendations = cursor.fetchone()[0]

        # Data sources used
        cursor.execute("""
            SELECT data_source, COUNT(*) as count
            FROM data_access_log
            GROUP BY data_source
        """)
        data_sources = {row[0]: row[1] for row in cursor.fetchall()}

        conn.close()

        return {
            "total_interactions": total_interactions,
            "interactions_by_type": by_type,
            "recommendations_last_30_days": recent_recommendations,
            "data_sources_accessed": data_sources,
            "retention_years": self.RETENTION_YEARS,
            "generated_at": datetime.utcnow().isoformat()
        }

    def export_audit_report(
        self,
        output_path: str,
        start_date: Optional[str] = None,
        end_date: Optional[str] = None
    ):
        """Export audit report to JSON file."""
        trail = self.get_audit_trail(
            start_date=start_date,
            end_date=end_date,
            limit=10000
        )

        summary = self.get_compliance_summary()

        report = {
            "report_type": "SEBI_COMPLIANCE_AUDIT",
            "generated_at": datetime.utcnow().isoformat(),
            "period": {
                "start": start_date,
                "end": end_date
            },
            "summary": summary,
            "interactions": trail,
            "disclaimer": DISCLAIMER_TEXT
        }

        with open(output_path, 'w') as f:
            json.dump(report, f, indent=2, default=str)

        self.logger.info(f"Exported audit report to {output_path}")
